version: "2"
run:
  timeout: 5m
  concurrency: 8
linters:
  enable:
    - cyclop
    - fatcontext
    - forbidigo
    - funcorder
    - funlen
    - goconst
    - gocritic
    - godot
    - gosec
    - lll
    - misspell
    - modernize
    - nestif
    - revive
    - unparam
    - unused
    - whitespace
  settings:
    cyclop:
      max-complexity: 7
    revive:
      rules:
        - name: argument-limit
          arguments: [4]
